package redgear.brewcraft.plugins.common;

import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.potion.Potion;
import net.minecraftforge.fluids.FluidContainerRegistry;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;
import redgear.brewcraft.api.BrewingAPI;
import redgear.brewcraft.potions.FluidPotion;
import redgear.brewcraft.potions.MetaItemPotion;
import redgear.brewcraft.utils.PotionRegistry;
import redgear.core.fluids.FluidUtil;
import redgear.core.mod.IPlugin;
import redgear.core.mod.ModUtils;
import redgear.core.util.SimpleItem;
import cpw.mods.fml.common.LoaderState.ModState;

public class PotionPlugin implements IPlugin {

	public static MetaItemPotion potions;
	public static SimpleItem emptyBottle = new SimpleItem(Items.glass_bottle, 0);
	public static PotionRegistry registry = new PotionRegistry();
	public static final String potionTexture = "potionWhite";

	public static FluidStack fluidAwkward;
	public static FluidStack fluidVision;
	public static FluidStack fluidVisionLong;
	public static FluidStack fluidVisionVeryLong;
	public static FluidStack fluidInvisible;
	public static FluidStack fluidInvisibleLong;
	public static FluidStack fluidInvisibleVeryLong;
	public static FluidStack fluidWeakness;
	public static FluidStack fluidWeaknessLong;
	public static FluidStack fluidWeaknessVeryLong;
	public static FluidStack fluidFireResist;
	public static FluidStack fluidFireResistLong;
	public static FluidStack fluidFireResistVeryLong;
	public static FluidStack fluidSlowness;
	public static FluidStack fluidSlownessLong;
	public static FluidStack fluidSlownessVeryLong;
	public static FluidStack fluidRegen;
	public static FluidStack fluidRegenII;
	public static FluidStack fluidRegenIII;
	public static FluidStack fluidRegenLong;
	public static FluidStack fluidRegenVeryLong;
	public static FluidStack fluidFast;
	public static FluidStack fluidFastII;
	public static FluidStack fluidFastIII;
	public static FluidStack fluidFastLong;
	public static FluidStack fluidFastVeryLong;
	public static FluidStack fluidStrength;
	public static FluidStack fluidStrengthII;
	public static FluidStack fluidStrengthIII;
	public static FluidStack fluidStrengthLong;
	public static FluidStack fluidStrengthVeryLong;
	public static FluidStack fluidPoison;
	public static FluidStack fluidPoisonII;
	public static FluidStack fluidPoisonIII;
	public static FluidStack fluidPoisonLong;
	public static FluidStack fluidPoisonVeryLong;
	public static FluidStack fluidHaste;
	public static FluidStack fluidHasteII;
	public static FluidStack fluidHasteIII;
	public static FluidStack fluidHasteLong;
	public static FluidStack fluidHasteVeryLong;
	public static FluidStack fluidFatigue;
	public static FluidStack fluidFatigueII;
	public static FluidStack fluidFatigueIII;
	public static FluidStack fluidFatigueLong;
	public static FluidStack fluidFatigueVeryLong;
	public static FluidStack fluidJump;
	public static FluidStack fluidJumpII;
	public static FluidStack fluidJumpIII;
	public static FluidStack fluidJumpLong;
	public static FluidStack fluidJumpVeryLong;
	public static FluidStack fluidResistance;
	public static FluidStack fluidResistanceII;
	public static FluidStack fluidResistanceIII;
	public static FluidStack fluidResistanceLong;
	public static FluidStack fluidResistanceVeryLong;
	public static FluidStack fluidHunger;
	public static FluidStack fluidHungerII;
	public static FluidStack fluidHungerIII;
	public static FluidStack fluidHungerLong;
	public static FluidStack fluidHungerVeryLong;
	public static FluidStack fluidHealthBoost;
	public static FluidStack fluidHealthBoostII;
	public static FluidStack fluidHealthBoostIII;
	public static FluidStack fluidHealthBoostLong;
	public static FluidStack fluidHealthBoostVeryLong;
	public static FluidStack fluidAbsorption;
	public static FluidStack fluidAbsorptionII;
	public static FluidStack fluidAbsorptionIII;
	public static FluidStack fluidAbsorptionLong;
	public static FluidStack fluidAbsorptionVeryLong;
	public static FluidStack fluidSaturation;
	public static FluidStack fluidSaturationII;
	public static FluidStack fluidSaturationIII;
	public static FluidStack fluidSaturationLong;
	public static FluidStack fluidSaturationVeryLong;
	public static FluidStack fluidWither;
	public static FluidStack fluidWitherII;
	public static FluidStack fluidWitherIII;
	public static FluidStack fluidWitherLong;
	public static FluidStack fluidWitherVeryLong;
	public static FluidStack fluidHarm;
	public static FluidStack fluidHarmII;
	public static FluidStack fluidHarmIII;
	public static FluidStack fluidHeal;
	public static FluidStack fluidHealII;
	public static FluidStack fluidHealIII;
	public static FluidStack fluidWaterBreathe;
	public static FluidStack fluidWaterBreatheLong;
	public static FluidStack fluidWaterBreatheVeryLong;
	public static FluidStack fluidNausea;
	public static FluidStack fluidNauseaLong;
	public static FluidStack fluidNauseaVeryLong;
	public static FluidStack fluidBlindness;
	public static FluidStack fluidBlindnessLong;
	public static FluidStack fluidBlindnessVeryLong;
	public static FluidStack fluidFireImmunity;
	public static FluidStack fluidFireImmunityII;
	
	public static FluidStack fluidHolyWater;
	public static FluidStack fluidHolyWaterII;
	public static FluidStack fluidHolyWaterIII;
	public static FluidStack fluidHolyWaterLong;
	public static FluidStack fluidHolyWaterVeryLong;
	public static FluidStack fluidAntidote;
	public static FluidStack fluidAntidoteII;
	public static FluidStack fluidAntidoteIII;
	public static FluidStack fluidAntidoteLong;
	public static FluidStack fluidAntidoteVeryLong;
	public static FluidStack fluidFlight;
	public static FluidStack fluidFlightLong;
	public static FluidStack fluidFlightVeryLong;
	public static FluidStack fluidCryo;
	public static FluidStack fluidCryoLong;
	public static FluidStack fluidCryoVeryLong;
	public static FluidStack fluidBoom;
	public static FluidStack fluidBoomII;
	public static FluidStack fluidBoomIII;
	public static FluidStack fluidBoomLong;
	public static FluidStack fluidBoomVeryLong;

	@Override
	public String getName() {
		return "PotionPlugin";
	}

	@Override
	public boolean shouldRun(ModUtils mod, ModState state) {
		return true;
	}

	@Override
	public boolean isRequired() {
		return true;
	}

	@Override
	public void preInit(ModUtils mod) {
		potions = new MetaItemPotion("RedGear.Brewcraft.Potions"); // Items MUST be created in pre init! NO exceptions!
	}

	@Override
	public void Init(ModUtils mod) {
		fluidAwkward = createVanillaPotion("Awkward", 16, 0);
		System.out.println("Created at least one potion successfully.");
		fluidVision = createVanillaPotion("Vision", 8198, 16390);
		fluidVisionLong = createVanillaPotion("VisionLong", 8262, 16454);
		fluidInvisible = createVanillaPotion("Invisible", 8206, 16398);
		fluidInvisibleLong = createVanillaPotion("InvisibleLong", 8270, 16462);
		fluidRegen = createVanillaPotion("Regen", 8193, 16385);
		fluidRegenII = createVanillaPotion("RegenII", 8289, 16481);
		fluidRegenLong = createVanillaPotion("RegenLong", 8257, 16449);
		fluidFast = createVanillaPotion("Fast", 8194, 16386);
		fluidFastLong = createVanillaPotion("FastLong", 8290, 164500);
		fluidFastII = createVanillaPotion("FastII", 8258, 16418);
		fluidWeakness = createVanillaPotion("Weakness", 8200, 16392);
		fluidWeaknessLong = createVanillaPotion("WeaknessLong", 8264, 16456);
		fluidStrength = createVanillaPotion("Strength", 8201, 16393);
		fluidStrengthLong = createVanillaPotion("StrengthLong", 8265, 16457);
		fluidStrengthII = createVanillaPotion("StrengthII", 8297, 16425);
		fluidFireResist = createVanillaPotion("FireResist", 8195, 16387);
		fluidFireResistLong = createVanillaPotion("FireResistLong", 8259, 16451);
		fluidSlowness = createVanillaPotion("Slowness", 8202, 16394);
		fluidSlownessLong = createVanillaPotion("SlownessLong", 8266, 16458);
		fluidPoison = createVanillaPotion("Poison", 8196, 16388);
		fluidPoisonII = createVanillaPotion("PoisonII", 8260, 16420);
		fluidPoisonLong = createVanillaPotion("PoisonLong", 8228, 16452);
		fluidHarm = createVanillaPotion("Harm", 8204, 16396);
		fluidHarmII = createVanillaPotion("HarmII", 8236, 16428);
		fluidHeal = createVanillaPotion("Heal", 8196, 16389);
		fluidHealII = createVanillaPotion("HealII", 8229, 16421);
		fluidWaterBreathe = createVanillaPotion("WaterBreathe", 8205, 16397);
		fluidWaterBreatheLong = createVanillaPotion("WaterBreatheLong", 8269, 16461);

		fluidHaste = registry.addPotion("Haste", Potion.digSpeed, 90, 0, true);
		fluidHasteII = registry.addPotion("HasteII", Potion.digSpeed, 45, 1, true);
		fluidHasteIII = registry.addPotion("HasteIII", Potion.digSpeed, 25, 2, true);
		fluidHasteLong = registry.addPotion("HasteLong", Potion.digSpeed, 180, 0, true);
		fluidHasteVeryLong = registry.addPotion("HasteVeryLong", Potion.digSpeed, 360, 0, true);
		fluidFatigue = registry.addPotion("Fatigue", Potion.digSlowdown, 90, 0, true);
		fluidFatigueII = registry.addPotion("FatigueII", Potion.digSlowdown, 45, 1, true);
		fluidFatigueIII = registry.addPotion("FatigueIII", Potion.digSlowdown, 25, 2, true);
		fluidFatigueLong = registry.addPotion("FatigueLong", Potion.digSlowdown, 180, 0, true);
		fluidFatigueVeryLong = registry.addPotion("FatigueVeryLong", Potion.digSlowdown, 360, 0, true);
		fluidJump = registry.addPotion("Jump", Potion.jump, 60, 0, true);
		fluidJumpII = registry.addPotion("JumpII", Potion.jump, 30, 1, true);
		fluidJumpIII = registry.addPotion("JumpIII", Potion.jump, 15, 2, true);
		fluidJumpLong = registry.addPotion("JumpLong", Potion.jump, 120, 0, true);
		fluidJumpVeryLong = registry.addPotion("JumpVeryLong", Potion.jump, 240, 0, true);
		fluidNausea = registry.addPotion("Nausea", Potion.confusion, 30, 0);
		fluidNauseaLong = registry.addPotion("NauseaLong", Potion.confusion, 60, 0);
		fluidNauseaVeryLong = registry.addPotion("NauseaVeryLong", Potion.confusion, 120, 0);
		fluidResistance = registry.addPotion("Resistance", Potion.resistance, 90, 0, true);
		fluidResistanceII = registry.addPotion("ResistanceII", Potion.resistance, 45, 1, true);
		fluidResistanceIII = registry.addPotion("ResistanceIII", Potion.resistance, 20, 2, true);
		fluidResistanceLong = registry.addPotion("ResistanceLong", Potion.resistance, 180, 0, true);
		fluidResistanceVeryLong = registry.addPotion("ResistanceVeryLong", Potion.resistance, 360, 0, true);
		fluidBlindness = registry.addPotion("Blindness", Potion.blindness, 30, 0);
		fluidBlindnessLong = registry.addPotion("BlindnessLong", Potion.blindness, 60, 0);
		fluidBlindnessVeryLong = registry.addPotion("BlindnessVeryLong", Potion.blindness, 120, 0);
		fluidHunger = registry.addPotion("Hunger", Potion.hunger, 60, 0);
		fluidHungerII = registry.addPotion("HungerII", Potion.hunger, 30, 1);
		fluidHungerIII = registry.addPotion("HungerIII", Potion.hunger, 15, 2);
		fluidHungerLong = registry.addPotion("HungerLong", Potion.hunger, 120, 0);
		fluidHungerVeryLong = registry.addPotion("HungerVeryLong", Potion.hunger, 240, 0);
		fluidHealthBoost = registry.addPotion("HealthBoost", Potion.field_76434_w, 120, 0, true);
		fluidHealthBoostII = registry.addPotion("HealthBoostII", Potion.field_76434_w, 60, 1, true);
		fluidHealthBoostIII = registry.addPotion("HealthBoostIII", Potion.field_76434_w, 30, 2, true);
		fluidHealthBoostLong = registry.addPotion("HealthBoostLong", Potion.field_76434_w, 240, 0, true);
		fluidHealthBoostVeryLong = registry.addPotion("HealthBoostVeryLong", Potion.field_76434_w, 480, 0, true);
		fluidAbsorption = registry.addPotion("Absorption", Potion.field_76444_x, 60, 0);
		fluidAbsorptionII = registry.addPotion("AbsorptionII", Potion.field_76444_x, 30, 1);
		fluidAbsorptionIII = registry.addPotion("AbsorptionIII", Potion.field_76444_x, 15, 2);
		fluidAbsorptionLong = registry.addPotion("AbsorptionLong", Potion.field_76444_x, 120, 0);
		fluidAbsorptionVeryLong = registry.addPotion("AbsorptionVeryLong", Potion.field_76444_x, 240, 0);
		fluidSaturation = registry.addPotion("Saturation", Potion.field_76443_y, 10, 0);
		fluidSaturationII = registry.addPotion("SaturationII", Potion.field_76443_y, 5, 1);
		fluidSaturationIII = registry.addPotion("SaturationIII", Potion.field_76443_y, 3, 2);
		fluidSaturationLong = registry.addPotion("SaturationLong", Potion.field_76443_y, 20, 0);
		fluidSaturationVeryLong = registry.addPotion("SaturationVeryLong", Potion.field_76443_y, 40, 0);
		fluidWither = registry.addPotion("Wither", Potion.wither, 20, 0);
		fluidWitherII = registry.addPotion("WitherII", Potion.wither, 10, 1);
		fluidWitherIII = registry.addPotion("WitherIII", Potion.wither, 5, 2);
		fluidWitherLong = registry.addPotion("WitherLong", Potion.wither, 40, 0);
		fluidWitherVeryLong = registry.addPotion("WitherVeryLong", Potion.wither, 80, 0);

		fluidHolyWater = registry.addPotion("HolyWater", EffectPlugin.angel, 10, 0, true);
		fluidHolyWaterII = registry.addPotion("HolyWaterII", EffectPlugin.angel, 5, 1, true);
		fluidHolyWaterLong = registry.addPotion("HolyWaterLong", EffectPlugin.angel, 10, 0, true);
		fluidHolyWaterVeryLong = registry.addPotion("HolyWaterVeryLong", EffectPlugin.angel, 20, 0, true);
		fluidHolyWaterIII = registry.addPotion("HolyWaterIII", EffectPlugin.angel, 3, 2, true);
		fluidFlight = registry.addPotion("Flight", EffectPlugin.flight, 15, 0);
		fluidFlightLong = registry.addPotion("FlightLong", EffectPlugin.flight, 30, 0);
		fluidFlightVeryLong = registry.addPotion("FlightVeryLong", EffectPlugin.flight, 60, 0);
		fluidAntidote = registry.addPotion("Antidote", EffectPlugin.immunity, 60, 0, true);
		fluidAntidoteII = registry.addPotion("AntidoteII", EffectPlugin.immunity, 45, 1, true);
		fluidAntidoteIII = registry.addPotion("AntidoteIII", EffectPlugin.immunity, 30, 2, true);
		fluidAntidoteLong = registry.addPotion("AntidoteLong", EffectPlugin.immunity, 120, 0, true);
		fluidAntidoteVeryLong = registry.addPotion("AntidoteVeryLong", EffectPlugin.immunity, 240, 0, true);
		fluidBoom = registry.addPotion("Boom", EffectPlugin.creeper, 8, 0, true);
		fluidBoomII = registry.addPotion("BoomII", EffectPlugin.creeper, 4, 1, true);
		fluidBoomIII = registry.addPotion("BoomIII", EffectPlugin.creeper, 4, 2, true);
		fluidBoomLong = registry.addPotion("BoomLong", EffectPlugin.creeper, 16, 0, true);
		fluidBoomVeryLong = registry.addPotion("BoomVeryLong", EffectPlugin.creeper, 32, 0, true);
		fluidCryo = registry.addPotion("Cryo", EffectPlugin.frozen, 8, 0, true);
		fluidCryoLong = registry.addPotion("CryoLong", EffectPlugin.frozen, 16, 0, true);
		fluidCryoVeryLong = registry.addPotion("CryoVeryLong", EffectPlugin.frozen, 30, 0, true);

		fluidRegenIII = registry.addPotion("RegenIII", Potion.regeneration, 8, 2);
		fluidRegenVeryLong = registry.addPotion("RegenVeryLong", Potion.regeneration, 180, 0);
		fluidFastIII = registry.addPotion("FastIII", Potion.moveSpeed, 8, 2, true);
		fluidFastVeryLong = registry.addPotion("FastVeryLong", Potion.moveSpeed, 960, 0);
		fluidStrengthIII = registry.addPotion("StrengthIII", Potion.damageBoost, 40, 2, true);
		fluidStrengthVeryLong = registry.addPotion("StrengthVeryLong", Potion.damageBoost, 960, 0);
		fluidFireImmunity = registry.addPotion("FireImmunity", EffectPlugin.fireproof, 35, 0, true);
		fluidFireImmunityII = registry.addPotion("FireImmunityII", EffectPlugin.fireproof, 15, 1, true);
		fluidFireResistVeryLong = registry.addPotion("FireResistVeryLong", Potion.fireResistance, 960, 0);
		fluidPoisonIII = registry.addPotion("PoisonIII", Potion.poison, 8, 2);
		fluidPoisonVeryLong = registry.addPotion("PoisonVeryLong", Potion.poison, 240, 0);
		fluidHarmIII = registry.addPotion( "HarmIII", Potion.harm, 1, 2);
		fluidHealIII = registry.addPotion("HealIII", Potion.heal, 1, 2);
		fluidVisionVeryLong = registry.addPotion("VisionVeryLong", Potion.nightVision, 960, 0);
		fluidWeaknessVeryLong = registry.addPotion("WeaknessVeryLong", Potion.weakness, 480, 0, true);
		fluidSlownessVeryLong = registry.addPotion("SlownessVeryLong", Potion.moveSlowdown, 480, 0, true);
		fluidWaterBreatheVeryLong = registry.addPotion("WaterBreatheVeryLong", Potion.waterBreathing, 960, 0);
		
		fluidRegenIII = registry.addPotion("RegenIII", Potion.regeneration, 8, 2);
		fluidRegenVeryLong = registry.addPotion("RegenVeryLong", Potion.regeneration, 180, 0);
		fluidFastIII = registry.addPotion("FastIII", Potion.moveSpeed, 8, 2, true);
		fluidFastVeryLong = registry.addPotion("FastVeryLong", Potion.moveSpeed, 960, 0);
		fluidStrengthIII = registry.addPotion("StrengthIII", Potion.damageBoost, 40, 2, true);
		fluidStrengthVeryLong = registry.addPotion("StrengthVeryLong", Potion.damageBoost, 960, 0);
		fluidFireImmunity = registry.addPotion("FireImmunity", EffectPlugin.fireproof, 35, 0, true);
		fluidFireImmunityII = registry.addPotion("FireImmunityII", EffectPlugin.fireproof, 15, 1, true);
		fluidFireResistVeryLong = registry.addPotion("FireResistVeryLong", Potion.fireResistance, 960, 0);
		fluidPoisonIII = registry.addPotion("PoisonIII", Potion.poison, 8, 2);
		fluidPoisonVeryLong = registry.addPotion("PoisonVeryLong", Potion.poison, 240, 0);
		fluidHarmIII = registry.addPotion("HarmIII", Potion.harm, 1, 2);
		fluidHealIII = registry.addPotion("HealIII", Potion.heal, 1, 2);
		fluidVisionVeryLong = registry.addPotion("VisionVeryLong", Potion.nightVision, 960, 0);
		fluidWeaknessVeryLong = registry.addPotion("WeaknessVeryLong", Potion.weakness, 480, 0, true);
		fluidSlownessVeryLong = registry.addPotion("SlownessVeryLong", Potion.moveSlowdown, 480, 0, true);
		fluidWaterBreatheVeryLong = registry.addPotion("WaterBreatheVeryLong", Potion.waterBreathing, 960, 0);
	}

	@Override
	public void postInit(ModUtils mod) {
		BrewingAPI.RECIPE_REGISTRY.addRecipe(new FluidStack(FluidRegistry.WATER, 100), fluidAwkward, new ItemStack(Items.nether_wart));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidFireResist, new ItemStack(Items.magma_cream));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidFast, new ItemStack(Items.sugar));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidHeal, new ItemStack(Items.speckled_melon));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidPoison, new ItemStack(Items.spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidRegen, new ItemStack(Items.ghast_tear));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidStrength, new ItemStack(Items.blaze_powder));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidWeakness, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidVision, new ItemStack(Items.golden_carrot));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidWaterBreathe, new ItemStack(Items.fish, 1, 3));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFireResist, fluidFireResistLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFireResistLong, fluidFireResistVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHeal, fluidHealII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHealII, fluidHealIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidRegen, fluidRegenLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidRegenLong, fluidRegenVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidRegen, fluidRegenII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidRegenII, fluidRegenIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidStrength, fluidStrengthII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidStrengthII, fluidStrengthIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidStrength, fluidStrengthLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidStrengthLong, fluidStrengthVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFast, fluidFastLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFastLong, fluidFastVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFast, fluidFastII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFastII, fluidFastIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidVision, fluidVisionLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidVisionLong, fluidVisionVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidVision, fluidInvisible, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidVisionLong, fluidInvisibleLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidVisionVeryLong, fluidInvisibleVeryLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidInvisible, fluidInvisibleLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidInvisibleLong, fluidInvisibleVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWaterBreathe, fluidWaterBreatheLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWaterBreatheLong, fluidWaterBreatheVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHeal, fluidHarm, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHealII, fluidHarmII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHealIII, fluidHarmIII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidPoison, fluidHarm, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidPoisonII, fluidHarmII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidPoisonIII, fluidHarmIII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHarm, fluidHarmII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidPoison, fluidPoisonLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidPoison, fluidPoisonII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidVisionLong, fluidInvisibleLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFireResist, fluidSlowness, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFireResistLong, fluidSlownessLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFast, fluidSlowness, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFastLong, fluidSlownessLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFastVeryLong, fluidSlownessVeryLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSlowness, fluidSlownessLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidStrength, fluidWeakness, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidStrengthLong, fluidWeaknessLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidStrengthVeryLong, fluidWeaknessVeryLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidRegen, fluidWeakness, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidRegenLong, fluidWeaknessLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidRegenVeryLong, fluidWeaknessVeryLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHealII, fluidHeal, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHarmII, fluidHeal, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFireResistLong, fluidFireResist, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSlownessLong, fluidSlowness, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWeaknessLong, fluidWeakness, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWaterBreatheLong, fluidWaterBreathe, new ItemStack(Items.glowstone_dust));
		
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidRegen, fluidHolyWater, IngredientPlugin.holyDust.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidRegenII, fluidHolyWaterII, IngredientPlugin.holyDust.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidRegenIII, fluidHolyWaterIII, IngredientPlugin.holyDust.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidRegenLong, fluidHolyWaterLong, IngredientPlugin.holyDust.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidRegenVeryLong, fluidHolyWaterVeryLong, IngredientPlugin.holyDust.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHolyWater, fluidHarm, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHolyWaterII, fluidHarmII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHolyWaterIII, fluidHarmIII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHolyWater, fluidHolyWaterII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHolyWater, fluidHolyWaterLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHolyWaterII, fluidHolyWaterIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHolyWaterLong, fluidHolyWaterVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidFlight, IngredientPlugin.goldenFeather.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidote, fluidAntidoteII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidote, fluidAntidoteLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidoteII, fluidAntidoteIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidoteLong, fluidAntidoteVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWither, fluidBoom, new ItemStack(Items.gunpowder));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWitherII, fluidBoomII, new ItemStack(Items.gunpowder));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWitherIII, fluidBoomIII, new ItemStack(Items.gunpowder));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWitherLong, fluidBoomLong, new ItemStack(Items.gunpowder));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWitherVeryLong, fluidBoomVeryLong, new ItemStack(Items.gunpowder));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidBoom, fluidBoomII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidBoom, fluidBoomLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidBoomII, fluidBoomIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidBoomLong, fluidBoomVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSlowness, fluidCryo, new ItemStack(Items.snowball));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSlownessLong, fluidCryoLong, new ItemStack(Items.snowball));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSlownessVeryLong, fluidCryoVeryLong, new ItemStack(Items.snowball));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSlowness, fluidSlownessLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSlownessLong, fluidSlownessVeryLong, IngredientPlugin.pureTear.getStack());
		
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidNausea, new ItemStack(Items.poisonous_potato));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidNausea, fluidNauseaLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidNauseaLong, fluidNausea, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidNauseaLong, fluidNauseaVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidBlindness, new ItemStack(Items.dye, 1, 0));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidBlindness, fluidBlindnessLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidBlindnessLong, fluidBlindnessVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidBlindness, fluidVision, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidBlindnessLong, fluidVisionLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidBlindnessVeryLong, fluidVisionVeryLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidHunger, new ItemStack(Items.rotten_flesh));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHunger, fluidHungerII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHunger, fluidHungerLong, new ItemStack(Items.rotten_flesh));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHungerII, fluidHungerIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHungerLong, fluidHungerVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHunger, fluidSaturation, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHungerII, fluidSaturationII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHungerIII, fluidSaturationIII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHungerLong, fluidSaturationLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHungerVeryLong, fluidSaturationVeryLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidSaturation, new ItemStack(Items.cake));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHunger, fluidSaturation, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSaturation, fluidHunger, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHungerII, fluidSaturationII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSaturationII, fluidHungerII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHungerIII, fluidSaturationIII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSaturationIII, fluidHungerIII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHungerLong, fluidSaturationLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSaturationLong, fluidHungerLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHungerVeryLong, fluidSaturationVeryLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSaturationVeryLong, fluidHungerVeryLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSaturation, fluidSaturationII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSaturationII, fluidSaturationIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSaturation, fluidSaturationLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidSaturationLong, fluidSaturationVeryLong, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidHaste, IngredientPlugin.spiderFang.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFatigue, fluidHaste, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHaste, fluidFatigue, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFatigueII, fluidHasteII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHasteII, fluidFatigueII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFatigueIII, fluidHasteIII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHasteIII, fluidFatigueIII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFatigueLong, fluidHasteLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHasteLong, fluidFatigueLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFatigueVeryLong, fluidHasteVeryLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHasteVeryLong, fluidFatigueVeryLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHaste, fluidHasteII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHasteII, fluidHaste, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHasteLong, fluidHaste, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHasteII, fluidHasteIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHaste, fluidHasteLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHasteLong, fluidHasteVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFatigue, fluidHaste, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidFatigue, IngredientPlugin.tiredSpores.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFatigue, fluidFatigueII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFatigueII, fluidFatigue, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFatigueII, fluidFatigueIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFatigue, fluidFatigueLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFatigueLong, fluidFatigue, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidFatigueLong, fluidFatigueVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidHealthBoost, IngredientPlugin.heartGold.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHealthBoost, fluidHealthBoostII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHealthBoostII, fluidHealthBoost, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHealthBoostII, fluidHealthBoostIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHealthBoost, fluidHealthBoostLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHealthBoostLong, fluidHealthBoost, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidHealthBoostLong, fluidHealthBoostVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidAntidote, IngredientPlugin.remedySalve.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidote, fluidAntidoteII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidoteII, fluidAntidote, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidoteII, fluidAntidoteIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidote, fluidAntidoteLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidoteLong, fluidAntidote, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidoteLong, fluidAntidoteVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidote, fluidWither, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWither, fluidAntidote, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidoteII, fluidWitherII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWitherII, fluidAntidoteII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidoteIII, fluidWitherIII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWitherIII, fluidAntidoteIII, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidoteLong, fluidWitherLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWitherLong, fluidAntidoteLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAntidoteVeryLong, fluidWitherVeryLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWitherVeryLong, fluidAntidoteVeryLong, new ItemStack(Items.fermented_spider_eye));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidJump, new ItemStack(Items.carrot));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidJump, fluidJumpII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidJumpII, fluidJump, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidJumpII, fluidJumpIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidJump, fluidJumpLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidJumpLong, fluidJump, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidJumpLong, fluidJumpVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(new FluidStack(FluidRegistry.LAVA, 100), fluidWither, IngredientPlugin.charredBone.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWither, fluidWitherII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWitherII, fluidWitherIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWither, fluidWitherLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWitherLong, fluidWitherVeryLong, IngredientPlugin.pureTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWitherII, fluidWither, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidWitherLong, fluidWither, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAwkward, fluidAbsorption, IngredientPlugin.heartSmall.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAbsorption, fluidAbsorptionII, new ItemStack(Items.glowstone_dust));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAbsorptionII, fluidAbsorption, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAbsorptionII, fluidAbsorptionIII, IngredientPlugin.obsidianTear.getStack());
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAbsorption, fluidAbsorptionLong, new ItemStack(Items.redstone));
		BrewingAPI.RECIPE_REGISTRY.addRecipe(fluidAbsorptionLong, fluidAbsorption, new ItemStack(Items.glowstone_dust));
	}

	private FluidStack createVanillaPotion(String name, int metaBottle, int metaSplash) {
		FluidStack potion = new FluidStack(FluidUtil.createFluid(new FluidPotion("potion" + name, new SimpleItem(
				Items.potionitem, metaBottle)), potionTexture), 100);
		createVanillaPotion(potion, metaBottle, metaSplash);
		return potion;
	}

	private FluidStack createVanillaPotion(FluidStack potion, int metaBottle, int metaSplash) {
		FluidContainerRegistry.registerFluidContainer(potion, new ItemStack(Items.potionitem, 1, metaBottle),
				emptyBottle.getStack());
		if (metaSplash != 0)
			FluidContainerRegistry.registerFluidContainer(potion, new ItemStack(Items.potionitem, 1, metaSplash),
					IngredientPlugin.splashBottle.getStack());
		return potion;
	}
}
